rail_joint_1_position_controller:
  type: position_controllers/JointPositionController
  joint: rail_joint_1
  pid: {p: 100.0, i: 0.01, d: 10.0}

rail_joint_2_position_controller:
  type: position_controllers/JointPositionController
  joint: rail_joint_2
  pid: {p: 100.0, i: 0.01, d: 10.0}

rail_joint_3_position_controller:
  type: position_controllers/JointPositionController
  joint: rail_joint_3
  pid: {p: 100.0, i: 0.01, d: 10.0}

# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

manipulator:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  gains:
    joint1: {p: 100.0, i: 0.01, d: 10.0}
    joint2: {p: 100.0, i: 0.01, d: 10.0}
    joint3: {p: 100.0, i: 0.01, d: 10.0}
    joint4: {p: 100.0, i: 0.01, d: 10.0}
    joint5: {p: 100.0, i: 0.01, d: 10.0}

gripper:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint6
  gains:
    joint6: {p: 1.0, i: 0.0, d: 0.05}

# gazebo_ros_control:
#   pid_gains:
#     # joint1: {p: 5.0, i: 0.0, d: 0.2}
#     # joint2: {p: 5.0, i: 0.0, d: 0.2}
#     # joint3: {p: 3.0, i: 0.0, d: 0.1}
#     # joint4: {p: 3.0, i: 0.0, d: 0.1}
#     # joint5: {p: 2.0, i: 0.0, d: 0.1}
#     # joint6: {p: 1.0, i: 0.0, d: 0.05}
#     joint1: {p: 100,  d: 1, i: 1, i_clamp: 1}
#     joint2: {p: 100,  d: 1, i: 1, i_clamp: 1}
#     joint3: {p: 100,  d: 1, i: 1, i_clamp: 1}
#     joint4: {p: 100,  d: 1, i: 1, i_clamp: 1}
#     joint5: {p: 10,  d: 1, i: 1, i_clamp: 1}
#     joint6: {p: 10,  d: 1, i: 1, i_clamp: 1}
